name: Fastest Furs Error Pages

on:
  push:
    paths:
      - 'fastestfurs/**'
  pull_request:
    paths:
      - 'fastestfurs/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node_version: 12

      - name: Setup Yarn Environment
        run: |
          cd fastestfurs/
          yarn install

      # Run tests here

      - name: Compile Pug & Sass Files
        run: |
          cd fastestfurs/
          yarn build

      - name: Compress Files for Distribution
        run: |
          cd fastestfurs/
          mkdir error_pages
          mv *.html *.css error_pages/
          VERSION=$(jq .version package.json)
          tar czf error_pages-$VERSION.tar.gz error_pages/
          tar cjf error_pages-$VERSION.tar.bz2 error_pages/

      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Upload Release Asset \#1
        id: upload-release-asset-1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./error-pages-*.tar.gz
          asset_name: ./error-pages.tar.gz
          asset_content_type: application/x-gtar

      - name: Upload Release Asset \#2
        id: upload-release-asset-2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./error-pages-*.tar.bz2
          asset_name: ./error-pages.tar.bz2
          asset_content_type: application/x-gtar